#!/bin/bash
## This file tests all maps from maps/good and outputs info to output_goodfiles.log
## Don't forget to check permissions after a git pull!

# Directory containing files
directory="maps/good"

# Output log file for good files
output_log="output_goodfiles.log"

# Delete previous output_log
rm $output_log

# Iterate over each file in the directory
echo "Running good maps tester..."
for file in "$directory"/*; do
    # Check if the file is a regular file
    if [ -f "$file" ]; then
        echo "Running valgrind on $file..." >> "$output_log" 2>&1
        valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes -q ./cub3D "$file" >> "$output_log" 2>&1
		echo -e "\n\n" >> "$output_log" 2>&1
    fi
done
echo "Done!"